export enum FilterParam {
  CREATED_ON = 'createdOn',
  CREATED_ON_MIN = 'createdOnMin',
  CREATED_ON_MAX = 'createdOnMax',
  PAGE = 'page',
  LIMIT = 'limit',
  QUERY = 'query',
  TAG_TYPE = 'tagType',
  ASSIGN_IDS = 'assignIds',
  ACTIVE = 'active',
  MODE = 'mode',
  TYPE = 'type',
  RECEIVE_IDS = 'receiveIds',
  VARIANT_IDS = 'variantIds',
  WAREHOUSE_IDS = 'warehouseIds',
  REPORT_DATE = 'reportDate',
  REPORT_DATE_MIN = 'reportDateMin',
  REPORT_DATE_MAX = 'reportDateMax',
  SORTBY = 'sortBy',
  ORDER_STATUS = 'orderStatus',
  RECEIVE_STATUS = 'receiveStatus',
  RECEIVE_TRANSACTION_STATUS = 'receiveTransactionStatus',
  IS_EMPLOYED = 'isEmployed',
  ROLE = 'role',
  DIRECTION = 'direction',
  ORDER_BY = 'orderBy',
}

export type QueryParams = Partial<Record<FilterParam, string>>;
